# Generated by Django 3.1.7 on 2021-04-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='ono',
            field=models.IntegerField(default=500605, unique=True),
        ),
    ]
