# Generated by Django 3.1.7 on 2021-04-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20210415_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.URLField(),
        ),
    ]
