# Generated by Django 3.1.7 on 2021-04-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20210429_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='ono',
            field=models.IntegerField(default=258403, unique=True),
        ),
    ]
