# Generated by Django 3.1.7 on 2021-04-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20210415_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
    ]
