# Generated by Django 3.1.7 on 2021-04-25 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'Order Received'), ('C', 'Cooking'), ('P', 'Packed and Out For Delivery'), ('D', 'Delivered')], default='R', max_length=5),
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('osid', models.AutoField(primary_key=True, serialize=False)),
                ('ono', models.IntegerField(default=893758, unique=True)),
                ('date', models.DateField()),
                ('itemslist', models.TextField()),
                ('total', models.IntegerField()),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.restaurant')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
