# Generated by Django 3.1.7 on 2021-04-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_auto_20210425_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='status',
            field=models.CharField(choices=[('R', 'Order Received'), ('C', 'Cooking'), ('P', 'Packed and Out For Delivery'), ('D', 'Delivered')], default='R', max_length=5),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='ono',
            field=models.IntegerField(default=517916, unique=True),
        ),
    ]
