# Generated by Django 3.1.7 on 2021-04-28 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_auto_20210425_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='ono',
            field=models.IntegerField(default=509178, unique=True),
        ),
    ]
